#ifndef NU_GRAPHICS_SHARED_TYPES_H
#define NU_GRAPHICS_SHARED_TYPES_H

typedef enum
{
    NU_RENDERPASS_UNLIT,
    NU_RENDERPASS_FLAT,
    NU_RENDERPASS_TRANSPARENT,
    NU_RENDERPASS_SKYBOX,
} nu_renderpass_type_t;

#endif
